### ISSUE TITLE
Error URI malformed when running Remix application and Hot reloading not working

### ISSUE THREAD

**Issue by teodorazhelyazkova** [PaulBratslavsky/freecodecamp-remix-strapi-final#2]
I am trying to run the Remix app locally. After running npm run dev and opening http://localhost:5173/ I get the following error without even interacting with the page:

```
12:53:02 PM [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at viteTransformMiddleware (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:63657:19)
      at call (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42944:7)
      at next (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42888:5)
      at viteServePublicMiddleware (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53542:20)
      at call (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42944:7)
      at next (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42888:5)
      at viteHMRPingMiddleware (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:65046:13)
      at call (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42944:7)
      at next (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42888:5)
      at next (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42866:14)
      at viteCachedTransformMiddleware (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:63642:9)
      at call (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42944:7)
      at next (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42888:5)
      at cors (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:43416:7)
      at file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:43452:17
      at originCallback (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:43442:15)
      at file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:43447:13
      at optionsCallback (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:43427:9)
      at corsMiddleware (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:43432:7)
      at call (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42944:7)
      at next (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42888:5)
      at Function.handle (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42891:3)
      at Server.app (file:///C:/Users/anted/Documents/GitHub/remix-strapi-contacts-app/remix-contacts-app/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:42756:37)
      at Server.emit (node:events:513:28)
      at parserOnIncoming (node:_http_server:1072:12)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

```
I checked the suggested solution [here](https://stackoverflow.com/questions/72396236/error-uri-malformed-when-running-react-application-on-mac) but we don't have a "public/index.html" file from where to remove "%PUBLIC_URL%"

Also, the hot reloading of the project is not working, I should always refresh the page. I am not sure what is the issue with the configuration for that. I followed your tutorial as it is.

Here is my [repo](https://github.com/teodorazhelyazkova/remix-contacts-app) if you need more context.

Do you have any suggestions on how to fix those issues? Thanks in advance!

**Comment by PaulBratslavsky** [comment]
Can you share a link to your repo I will check it out.

**Comment by teodorazhelyazkova** [comment]
> Can you share a link to your repo I will check it out.

Yes, sure, thanks a lot for your time spent on this issue! I think I've linked it above as well but [here it is again](https://github.com/teodorazhelyazkova/remix-contacts-app)

Also, I've opened an issue in StackOverFlow and one contributor even opened a PR with a proposed solution, to generate Strapi token and add it to the app which I did but I still get the same error. You can check the PR [here](https://github.com/teodorazhelyazkova/remix-contacts-app/pull/1)

**Comment by teodorazhelyazkova** [comment]
@PaulBratslavsky Hi Paul, did you have time to check this issue or the other I have opened 1. [Form input value in contacts/create not saved]( https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final/issues/3) and 2. [Reloading page when adding a contact to favourites](https://github.com/PaulBratslavsky/freecodecamp-remix-strapi-final/issues/4)

**Comment by teodorazhelyazkova** [comment]
This issue was solved with the following [fix](https://github.com/teodorazhelyazkova/remix-contacts-app/pull/2)
